# Generated by Django 4.2.2 on 2023-06-16 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование агента')),
                ('number', models.CharField(max_length=20, verbose_name='Номер авто')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата заказа')),
                ('name1', models.CharField(max_length=255, verbose_name='Перевозчик')),
                ('name2', models.CharField(max_length=255, verbose_name='Водитель')),
                ('name3', models.CharField(max_length=255, verbose_name='Пользователь')),
            ],
        ),
    ]
